### PR TITLE
fixed zero team data exception but you'd better check stuffs twice in…

### PR DESCRIPTION
**Pull request by crimsonpython24**
… case i made errors

### CODE REVIEW

**Review by adl212 — CHANGES_REQUESTED** [review]
Don't set self.data and self.info to a default dictionary EVEN when the daily, season, and all time stats don't show up. Also, make sure to make the changes to the racer class

**Comment by adl212** [comment]
What I'm basically saying is that self.data and self.info are crucial for the rest of the program and we cant default to a dictionary. In fact what his pull request is about is making sure the racing stats for the teams.players actually show up instead of resulting in the class entirely not working.

**Comment by crimsonpython24** [comment]
bruh was playing clash royale atm, sorry that i didn't see the message

**Comment by adl212** [comment]
Fix the stiff and create a new pull request. And dont merge either since I need to update the package files first.

**Pull request merged**
